# Generated by Django 6.0.4 on 2026-04-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_currency_stock_description_stock_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
